const UI_TRANSLATIONS = {
  en: {
    uiLang: "UI Language", stt: "Speech-to-Text Provider", tts: "Text-to-Speech Provider", lang: "Assistant Language", voice: "Assistant Voice Persona", llm: "AI Engine (LLM) Provider", inst: "Voice Assistant Instructions", user: "User Prompt", ai: "Voice Assistant Response", clear: "Clear Memory (ESC)", debug: "Enable Debug Inspector", statusReady: "READY", statusSubReady: "Press Spacebar or Click here to start recording", statusRec: "RECORDING...", statusSubRec: "Speak now. Press ENTER or Click here to send.", statusProc: "PROCESSING...", statusSubProc: "Transcribing and generating response...", statusSpeak: "AI SPEAKING...", statusSubSpeak: "Listen to the response (Click or Press Space to Interrupt)", statusErr: "ERROR", statusSubErr: "API Error. Check Inspector.", userPlaceholder: "Transcribed user speech will appear here...", aiPlaceholder: "Sanitized assistant response will appear here...", pasteKey: "Paste {provider} Key", reqKey: "Enter an API key for the selected model", credAvail: "Credits available", noCred: "No credits available", credLeft: "Credits: {rem} / {limit} chars left", ctrls: "<strong>[ SPACEBAR ]</strong> Record/Pause/Interrupt | <strong>[ ENTER ]</strong> Send | <strong>[ ESC ]</strong> Clear Memory", basic: "Basic", fast: "Fast", expressive: "Expressive", slow: "Slow", conversational: "Conversational", soft: "Soft", confident: "Confident", playful: "Playful", warm: "Warm", errMic: "Microphone access denied.", errKeys: "Please enter both Speech-to-Text and AI Engine API Keys.", licenseText: "MIT License"
  },
  es: {
    uiLang: "Idioma de la Interfaz", stt: "Proveedor de Voz a Texto", tts: "Proveedor de Texto a Voz", lang: "Idioma del Asistente", voice: "Persona de Voz del Asistente", llm: "Proveedor de Motor de IA (LLM)", inst: "Instrucciones del Asistente de Voz", user: "Mensaje del Usuario", ai: "Respuesta del Asistente de Voz", clear: "Borrar Memoria (ESC)", debug: "Habilitar Inspector de Depuración", statusReady: "LISTO", statusSubReady: "Presiona la barra espaciadora o haz clic aquí para empezar a grabar", statusRec: "GRABANDO...", statusSubRec: "Habla ahora. Presiona ENTER o haz clic aquí para enviar.", statusProc: "PROCESANDO...", statusSubProc: "Transcribiendo y generando respuesta...", statusSpeak: "IA HABLANDO...", statusSubSpeak: "Escucha la respuesta (Haz clic o presiona Espacio para interrumpir)", statusErr: "ERROR", statusSubErr: "Error de API. Revisa el Inspector.", userPlaceholder: "El habla transcrita del usuario aparecerá aquí...", aiPlaceholder: "La respuesta desinfectada del asistente aparecerá aquí...", pasteKey: "Pegar clave de {provider}", reqKey: "Ingresa una clave de API para el modelo seleccionado", credAvail: "Créditos disponibles", noCred: "Sin créditos disponibles", credLeft: "Créditos: {rem} / {limit} caracteres restantes", ctrls: "<strong>[ ESPACIO ]</strong> Grabar/Pausar/Interrumpir | <strong>[ ENTER ]</strong> Enviar | <strong>[ ESC ]</strong> Borrar Memoria", basic: "Básico", fast: "Rápido", expressive: "Expresiva", slow: "Lento", conversational: "Conversacional", soft: "Suave", confident: "Segura", playful: "Juguetona", warm: "Cálida", errMic: "Acceso al micrófono denegado.", errKeys: "Por favor, ingresa las claves de API de Voz a Texto y del Motor de IA.", licenseText: "Licencia MIT"
  },
  fr: {
    uiLang: "Langue de l'Interface", stt: "Fournisseur de Synthèse Vocale", tts: "Fournisseur de Texte par Voix", lang: "Langue de l'Assistant", voice: "Persona Vocal de l'Assistant", llm: "Fournisseur de Moteur IA (LLM)", inst: "Instructions de l'Assistant Vocal", user: "Message de l'Utilisateur", ai: "Réponse de l'Assistant Vocal", clear: "Effacer la Mémoire (ESC)", debug: "Activer l'Inspecteur de Débogage", statusReady: "PRÊT", statusSubReady: "Appuyez sur Espace ou cliquez ici pour commencer l'enregistrement", statusRec: "ENREGISTREMENT...", statusSubRec: "Parlez maintenant. Appuyez sur ENTRÉE ou cliquez ici pour envoyer.", statusProc: "TRAITEMENT...", statusSubProc: "Transcription et génération de la réponse en cours...", statusSpeak: "L'IA PARLE...", statusSubSpeak: "Écoutez la réponse (Cliquez ou appuyez sur Espace pour interrompre)", statusErr: "ERREUR", statusSubErr: "Erreur API. Vérifiez l'Inspecteur.", userPlaceholder: "Le discours transcrit de l'utilisateur apparaîtra ici...", aiPlaceholder: "La réponse nettoyée de l'assistant apparaîtra ici...", pasteKey: "Coller la clé {provider}", reqKey: "Entrez une clé API pour le modèle sélectionné", credAvail: "Crédits disponibles", noCred: "Aucun crédit disponible", credLeft: "Crédits : {rem} / {limit} caractères restants", ctrls: "<strong>[ ESPACE ]</strong> Enregistrer/Pause/Interrompre | <strong>[ ENTRÉE ]</strong> Envoyer | <strong>[ ÉCHAP ]</strong> Effacer la Mémoire", basic: "Basique", fast: "Rapide", expressive: "Expressive", slow: "Lent", conversational: "Conversationnel", soft: "Douce", confident: "Confiante", playful: "Enjouée", warm: "Chaleureuse", errMic: "Accès au microphone refusé.", errKeys: "Veuillez entrer les clés API de Synthèse Vocale et du Moteur IA.", licenseText: "Licence MIT"
  },
  de: {
    uiLang: "UI-Sprache", stt: "Speech-to-Text Anbieter", tts: "Text-to-Speech Anbieter", lang: "Assistentensprache", voice: "Stimme des Assistenten", llm: "KI-Engine (LLM) Anbieter", inst: "Anweisungen für den Sprachassistenten", user: "Benutzer-Eingabe", ai: "Antwort des Sprachassistenten", clear: "Speicher löschen (ESC)", debug: "Debug-Inspektor aktivieren", statusReady: "BEREIT", statusSubReady: "Drücken Sie die Leertaste oder klicken Sie hier, um die Aufnahme zu starten", statusRec: "AUFNAHME LÄUFT...", statusSubRec: "Sprechen Sie jetzt. Drücken Sie ENTER oder klicken Sie hier zum Senden.", statusProc: "VERARBEITUNG...", statusSubProc: "Transkribiere und generiere Antwort...", statusSpeak: "KI SPRICHT...", statusSubSpeak: "Hören Sie sich die Antwort an (Klicken oder Leertaste zum Unterbrechen)", statusErr: "FEHLER", statusSubErr: "API-Fehler. Inspektor prüfen.", userPlaceholder: "Transkribierte Benutzersprache wird hier angezeigt...", aiPlaceholder: "Bereinigte Assistentenantwort wird hier angezeigt...", pasteKey: "{provider}-Schlüssel einfügen", reqKey: "Geben Sie einen API-Schlüssel für das ausgewählte Modell ein", credAvail: "Guthaben verfügbar", noCred: "Kein Guthaben verfügbar", credLeft: "Guthaben: {rem} / {limit} Zeichen übrig", ctrls: "<strong>[ LEERTASTE ]</strong> Aufnahme/Pause/Unterbrechen | <strong>[ ENTER ]</strong> Senden | <strong>[ ESC ]</strong> Speicher löschen", basic: "Basis", fast: "Schnell", expressive: "Ausdrucksstark", slow: "Langsam", conversational: "Umgangssprachlich", soft: "Sanft", confident: "Selbstbewusst", playful: "Verspielt", warm: "Warm", errMic: "Zugriff auf das Mikrofon verweigert.", errKeys: "Bitte geben Sie sowohl Speech-to-Text als auch KI-Engine API-Schlüssel ein.", licenseText: "MIT-Lizenz"
  },
  it: {
    uiLang: "Lingua dell'Interfaccia", stt: "Fornitore Speech-to-Text", tts: "Fornitore Text-to-Speech", lang: "Lingua dell'Assistente", voice: "Voce dell'Assistente", llm: "Fornitore Motore IA (LLM)", inst: "Istruzioni dell'Assistente Vocale", user: "Prompt dell'Utente", ai: "Risposta dell'Assistente Vocale", clear: "Cancella Memoria (ESC)", debug: "Abilita Inspector di Debug", statusReady: "PRONTO", statusSubReady: "Premi la barra spaziatrice o clicca qui per avviare la registrazione", statusRec: "REGISTRAZIONE...", statusSubRec: "Parla ora. Premi INVIO o clicca qui per inviare.", statusProc: "ELABORAZIONE...", statusSubProc: "Trascrizione e generazione della risposta in corso...", statusSpeak: "IA IN ASCOLTO...", statusSubSpeak: "Ascolta la risposta (Clicca o premi Spazio per interrompere)", statusErr: "ERRORE", statusSubErr: "Errore API. Controlla l'Inspector.", userPlaceholder: "Il discorso trascritto dell'utente apparirà qui...", aiPlaceholder: "La risposta ripulita dell'assistente apparirà qui...", pasteKey: "Incolla chiave {provider}", reqKey: "Inserisci una chiave API per il modello selezionato", credAvail: "Crediti disponibili", noCred: "Nessun credito disponibile", credLeft: "Crediti: {rem} / {limit} caratteri rimasti", ctrls: "<strong>[ SPAZIO ]</strong> Registra/Pausa/Interrompi | <strong>[ INVIO ]</strong> Invia | <strong>[ ESC ]</strong> Cancella Memoria", basic: "Base", fast: "Veloce", expressive: "Espressiva", slow: "Lento", conversational: "Conversazionale", soft: "Morbida", confident: "Sicura", playful: "Giocosa", warm: "Calda", errMic: "Accesso al microfono negato.", errKeys: "Inserisci entrambe le chiavi API Speech-to-Text e Motore IA.", licenseText: "Licenza MIT"
  }
};

const extraLangs = ["tr", "fi", "pt", "nl", "pl", "ru", "ja", "zh", "ko", "hi", "sv", "bg", "ro", "ar", "cs", "el", "hr", "ms", "sk", "da", "ta", "uk", "hu", "no", "vi", "id", "tl"];
extraLangs.forEach(lang => {
  UI_TRANSLATIONS[lang] = Object.assign({}, UI_TRANSLATIONS.en);
});
