const UI_TRANSLATIONS = {
  en: {
    uiLang: "UI Language", stt: "Speech-to-Text Provider", tts: "Text-to-Speech Provider", lang: "Assistant Language", voice: "Assistant Voice Persona", llm: "AI Engine (LLM) Provider", inst: "Voice Assistant Instructions", user: "User Prompt", ai: "Voice Assistant Response", clear: "Clear Memory (ESC)", debug: "Enable Debug Inspector", statusReady: "READY", statusSubReady: "Press Spacebar or Click here to start recording", statusRec: "RECORDING...", statusSubRec: "Speak now. Press ENTER or Click here to send.", statusProc: "PROCESSING...", statusSubProc: "Transcribing and generating response...", statusSpeak: "AI SPEAKING...", statusSubSpeak: "Listen to the response (Click or Press Space to Interrupt)", statusErr: "ERROR", statusSubErr: "API Error. Check Inspector.", userPlaceholder: "Transcribed user speech will appear here...", aiPlaceholder: "Sanitized assistant response will appear here...", pasteKey: "Paste {provider} Key", reqKey: "Enter an API key for the selected model", credAvail: "Credits available", noCred: "No credits available", credLeft: "Credits: {rem} / {limit} chars left", ctrls: "<strong>[ SPACEBAR ]</strong> Record/Pause/Interrupt | <strong>[ ENTER ]</strong> Send | <strong>[ ESC ]</strong> Clear Memory", basic: "Basic", fast: "Fast", expressive: "Expressive", slow: "Slow", conversational: "Conversational", soft: "Soft", confident: "Confident", playful: "Playful", warm: "Warm", errMic: "Microphone access denied.", errKeys: "Please enter both Speech-to-Text and AI Engine API Keys."
  },
  es: {
    uiLang: "Idioma de la Interfaz", stt: "Proveedor de Voz a Texto", tts: "Proveedor de Texto a Voz", lang: "Idioma del Asistente", voice: "Persona de Voz del Asistente", llm: "Proveedor de Motor de IA (LLM)", inst: "Instrucciones del Asistente de Voz", user: "Mensaje del Usuario", ai: "Respuesta del Asistente de Voz", clear: "Borrar Memoria (ESC)", debug: "Habilitar Inspector de Depuración", statusReady: "LISTO", statusSubReady: "Presiona la barra espaciadora o haz clic aquí para empezar a grabar", statusRec: "GRABANDO...", statusSubRec: "Habla ahora. Presiona ENTER o haz clic aquí para enviar.", statusProc: "PROCESANDO...", statusSubProc: "Transcribiendo y generando respuesta...", statusSpeak: "IA HABLANDO...", statusSubSpeak: "Escucha la respuesta (Haz clic o presiona Espacio para interrumpir)", statusErr: "ERROR", statusSubErr: "Error de API. Revisa el Inspector.", userPlaceholder: "El habla transcrita del usuario aparecerá aquí...", aiPlaceholder: "La respuesta desinfectada del asistente aparecerá aquí...", pasteKey: "Pegar clave de {provider}", reqKey: "Ingresa una clave de API para el modelo seleccionado", credAvail: "Créditos disponibles", noCred: "Sin créditos disponibles", credLeft: "Créditos: {rem} / {limit} caracteres restantes", ctrls: "<strong>[ ESPACIO ]</strong> Grabar/Pausar/Interrumpir | <strong>[ ENTER ]</strong> Enviar | <strong>[ ESC ]</strong> Borrar Memoria", basic: "Básico", fast: "Rápido", expressive: "Expresiva", slow: "Lento", conversational: "Conversacional", soft: "Suave", confident: "Segura", playful: "Juguetona", warm: "Cálida", errMic: "Acceso al micrófono denegado.", errKeys: "Por favor, ingresa las claves de API de Voz a Texto y del Motor de IA."
  },
  fr: {
    uiLang: "Langue de l'Interface", stt: "Fournisseur de Synthèse Vocale", tts: "Fournisseur de Texte par Voix", lang: "Langue de l'Assistant", voice: "Persona Vocal de l'Assistant", llm: "Fournisseur de Moteur IA (LLM)", inst: "Instructions de l'Assistant Vocal", user: "Message de l'Utilisateur", ai: "Réponse de l'Assistant Vocal", clear: "Effacer la Mémoire (ESC)", debug: "Activer l'Inspecteur de Débogage", statusReady: "PRÊT", statusSubReady: "Appuyez sur Espace ou cliquez ici pour commencer l'enregistrement", statusRec: "ENREGISTREMENT...", statusSubRec: "Parlez maintenant. Appuyez sur ENTRÉE ou cliquez ici pour envoyer.", statusProc: "TRAITEMENT...", statusSubProc: "Transcription et génération de la réponse en cours...", statusSpeak: "L'IA PARLE...", statusSubSpeak: "Écoutez la réponse (Cliquez ou appuyez sur Espace pour interrompre)", statusErr: "ERREUR", statusSubErr: "Erreur API. Vérifiez l'Inspecteur.", userPlaceholder: "Le discours transcrit de l'utilisateur apparaîtra ici...", aiPlaceholder: "La réponse nettoyée de l'assistant apparaîtra ici...", pasteKey: "Coller la clé {provider}", reqKey: "Entrez une clé API pour le modèle sélectionné", credAvail: "Crédits disponibles", noCred: "Aucun crédit disponible", credLeft: "Crédits : {rem} / {limit} caractères restants", ctrls: "<strong>[ ESPACE ]</strong> Enregistrer/Pause/Interrompre | <strong>[ ENTRÉE ]</strong> Envoyer | <strong>[ ÉCHAP ]</strong> Effacer la Mémoire", basic: "Basique", fast: "Rapide", expressive: "Expressive", slow: "Lent", conversational: "Conversationnel", soft: "Douce", confident: "Confiante", playful: "Enjouée", warm: "Chaleureuse", errMic: "Accès au microphone refusé.", errKeys: "Veuillez entrer les clés API de Synthèse Vocale et du Moteur IA."
  },
  de: {
    uiLang: "UI-Sprache", stt: "Speech-to-Text Anbieter", tts: "Text-to-Speech Anbieter", lang: "Assistentensprache", voice: "Stimme des Assistenten", llm: "KI-Engine (LLM) Anbieter", inst: "Anweisungen für den Sprachassistenten", user: "Benutzer-Eingabe", ai: "Antwort des Sprachassistenten", clear: "Speicher löschen (ESC)", debug: "Debug-Inspektor aktivieren", statusReady: "BEREIT", statusSubReady: "Drücken Sie die Leertaste oder klicken Sie hier, um die Aufnahme zu starten", statusRec: "AUFNAHME LÄUFT...", statusSubRec: "Sprechen Sie jetzt. Drücken Sie ENTER oder klicken Sie hier zum Senden.", statusProc: "VERARBEITUNG...", statusSubProc: "Transkribiere und generiere Antwort...", statusSpeak: "KI SPRICHT...", statusSubSpeak: "Hören Sie sich die Antwort an (Klicken oder Leertaste zum Unterbrechen)", statusErr: "FEHLER", statusSubErr: "API-Fehler. Inspektor prüfen.", userPlaceholder: "Transkribierte Benutzersprache wird hier angezeigt...", aiPlaceholder: "Bereinigte Assistentenantwort wird hier angezeigt...", pasteKey: "{provider}-Schlüssel einfügen", reqKey: "Geben Sie einen API-Schlüssel für das ausgewählte Modell ein", credAvail: "Guthaben verfügbar", noCred: "Kein Guthaben verfügbar", credLeft: "Guthaben: {rem} / {limit} Zeichen übrig", ctrls: "<strong>[ LEERTASTE ]</strong> Aufnahme/Pause/Unterbrechen | <strong>[ ENTER ]</strong> Senden | <strong>[ ESC ]</strong> Speicher löschen", basic: "Basis", fast: "Schnell", expressive: "Ausdrucksstark", slow: "Langsam", conversational: "Umgangssprachlich", soft: "Sanft", confident: "Selbstbewusst", playful: "Verspielt", warm: "Warm", errMic: "Zugriff auf das Mikrofon verweigert.", errKeys: "Bitte geben Sie sowohl Speech-to-Text als auch KI-Engine API-Schlüssel ein."
  },
  it: {
    uiLang: "Lingua dell'Interfaccia", stt: "Fornitore Speech-to-Text", tts: "Fornitore Text-to-Speech", lang: "Lingua dell'Assistente", voice: "Voce dell'Assistente", llm: "Fornitore Motore IA (LLM)", inst: "Istruzioni dell'Assistente Vocale", user: "Prompt dell'Utente", ai: "Risposta dell'Assistente Vocale", clear: "Cancella Memoria (ESC)", debug: "Abilita Inspector di Debug", statusReady: "PRONTO", statusSubReady: "Premi la barra spaziatrice o clicca qui per avviare la registrazione", statusRec: "REGISTRAZIONE...", statusSubRec: "Parla ora. Premi INVIO o clicca qui per inviare.", statusProc: "ELABORAZIONE...", statusSubProc: "Trascrizione e generazione della risposta in corso...", statusSpeak: "IA IN ASCOLTO...", statusSubSpeak: "Ascolta la risposta (Clicca o premi Spazio per interrompere)", statusErr: "ERRORE", statusSubErr: "Errore API. Controlla l'Inspector.", userPlaceholder: "Il discorso trascritto dell'utente apparirà qui...", aiPlaceholder: "La risposta ripulita dell'assistente apparirà qui...", pasteKey: "Incolla chiave {provider}", reqKey: "Inserisci una chiave API per il modello selezionato", credAvail: "Crediti disponibili", noCred: "Nessun credito disponibile", credLeft: "Crediti: {rem} / {limit} caratteri rimasti", ctrls: "<strong>[ SPAZIO ]</strong> Registra/Pausa/Interrompi | <strong>[ INVIO ]</strong> Invia | <strong>[ ESC ]</strong> Cancella Memoria", basic: "Base", fast: "Veloce", expressive: "Espressiva", slow: "Lento", conversational: "Conversazionale", soft: "Morbida", confident: "Sicura", playful: "Giocosa", warm: "Calda", errMic: "Accesso al microfono negato.", errKeys: "Inserisci entrambe le chiavi API Speech-to-Text e Motore IA."
  },
  ja: {
    uiLang: "UI言語", stt: "音声認識プロバイダー", tts: "音声合成プロバイダー", lang: "アシスタント言語", voice: "アシスタントの声", llm: "AIエンジン (LLM) プロバイダー", inst: "音声アシスタントの指示", user: "ユーザープロンプト", ai: "音声アシスタントの応答", clear: "メモリをクリア (ESC)", debug: "デバッグインスペクターを有効化", statusReady: "準備完了", statusSubReady: "スペースキーを押すか、ここをクリックして録音を開始します", statusRec: "録音中...", statusSubRec: "話してください。ENTERを押すか、ここをクリックして送信します。", statusProc: "処理中...", statusSubProc: "文字起こしと応答を生成しています...", statusSpeak: "AI発話中...", statusSubSpeak: "応答を聞く (クリックまたはスペースキーで中断)", statusErr: "エラー", statusSubErr: "APIエラー。インスペクターを確認してください。", userPlaceholder: "文字起こしされたユーザーの音声がここに表示されます...", aiPlaceholder: "サニタイズされたアシスタントの応答がここに表示されます...", pasteKey: "{provider}キーを貼り付け", reqKey: "選択したモデルのAPIキーを入力してください", credAvail: "クレジット利用可能", noCred: "利用可能なクレジットがありません", credLeft: "クレジット: 残り {rem} / {limit} 文字", ctrls: "<strong>[ スペースキー ]</strong> 録音/一時停止/中断 | <strong>[ ENTER ]</strong> 送信 | <strong>[ ESC ]</strong> メモリをクリア", basic: "基本", fast: "速い", expressive: "表現豊か", slow: "遅い", conversational: "会話形式", soft: "柔らかい", confident: "自信に満ちた", playful: "遊び心のある", warm: "温かい", errMic: "マイクへのアクセスが拒否されました。", errKeys: "音声認識とAIエンジンの両方のAPIキーを入力してください。"
  },
  zh: {
    uiLang: "界面语言", stt: "语音转文本提供商", tts: "文本转语音提供商", lang: "助手语言", voice: "助手声音角色", llm: "AI 引擎 (LLM) 提供商", inst: "语音助手指令", user: "用户提示词", ai: "语音助手回复", clear: "清除内存 (ESC)", debug: "启用调试检查器", statusReady: "准备就绪", statusSubReady: "按空格键或点击此处开始录音", statusRec: "录音中...", statusSubRec: "请说话。按 ENTER 或点击此处发送。", statusProc: "处理中...", statusSubProc: "正在转录并生成回复...", statusSpeak: "AI 正在说话...", statusSubSpeak: "收听回复 (点击或按空格键中断)", statusErr: "错误", statusSubErr: "API 错误。请检查检查器。", userPlaceholder: "转录的用户语音将显示在这里...", aiPlaceholder: "清理后的助手回复将显示在这里...", pasteKey: "粘贴 {provider} 密钥", reqKey: "请输入所选模型的 API 密钥", credAvail: "额度可用", noCred: "无可用额度", credLeft: "额度：剩余 {rem} / {limit} 字符", ctrls: "<strong>[ 空格键 ]</strong> 录音/暂停/中断 | <strong>[ 回车键 ]</strong> 发送 | <strong>[ ESC ]</strong> 清除内存", basic: "基础", fast: "快速", expressive: "富有表现力", slow: "缓慢", conversational: "对话", soft: "柔和", confident: "自信", playful: "俏皮", warm: "温暖", errMic: "麦克风访问被拒绝。", errKeys: "请输入语音转文本和 AI 引擎的 API 密钥。"
  },
  ko: {
    uiLang: "UI 언어", stt: "음성-텍스트 변환(STT) 제공자", tts: "텍스트-음성 변환(TTS) 제공자", lang: "어시스턴트 언어", voice: "어시스턴트 음성 페르소나", llm: "AI 엔진 (LLM) 제공자", inst: "음성 어시스턴트 지침", user: "사용자 프롬프트", ai: "음성 어시스턴트 응답", clear: "메모리 지우기 (ESC)", debug: "디버그 인스펙터 활성화", statusReady: "준비 완료", statusSubReady: "스페이스바를 누르거나 여기를 클릭하여 녹음을 시작하세요", statusRec: "녹음 중...", statusSubRec: "지금 말씀하세요. ENTER를 누르거나 여기를 클릭하여 전송하세요.", statusProc: "처리 중...", statusSubProc: "음성을 텍스트로 변환하고 응답을 생성하는 중...", statusSpeak: "AI 말하는 중...", statusSubSpeak: "응답 듣기 (클릭하거나 스페이스바를 눌러 중단)", statusErr: "오류", statusSubErr: "API 오류. 인스펙터를 확인하세요.", userPlaceholder: "변환된 사용자 음성이 여기에 표시됩니다...", aiPlaceholder: "정리된 어시스턴트 응답이 여기에 표시됩니다...", pasteKey: "{provider} 키 붙여넣기", reqKey: "선택한 모델의 API 키를 입력하세요", credAvail: "크레딧 사용 가능", noCred: "사용 가능한 크레딧 없음", credLeft: "크레딧: {rem} / {limit}자 남음", ctrls: "<strong>[ 스페이스바 ]</strong> 녹음/일시정지/중단 | <strong>[ 엔터 ]</strong> 전송 | <strong>[ ESC ]</strong> 메모리 지우기", basic: "기본", fast: "빠름", expressive: "표현력 있는", slow: "느림", conversational: "대화형", soft: "부드러운", confident: "자신감 있는", playful: "장난스러운", warm: "따뜻한", errMic: "마이크 접근이 거부되었습니다.", errKeys: "음성-텍스트 변환 및 AI 엔진 API 키를 모두 입력하세요."
  },
  vi: {
    uiLang: "Ngôn ngữ Giao diện", stt: "Nhà cung cấp Chuyển giọng nói thành Văn bản", tts: "Nhà cung cấp Chuyển Văn bản thành Giọng nói", lang: "Ngôn ngữ Trợ lý", voice: "Tính cách Giọng nói Trợ lý", llm: "Nhà cung cấp Mô hình Ngôn ngữ AI (LLM)", inst: "Hướng dẫn dành cho Trợ lý Giọng nói", user: "Lời nhắc của Người dùng", ai: "Phản hồi của Trợ lý Giọng nói", clear: "Xóa Bộ nhớ (ESC)", debug: "Bật Trình kiểm tra Gỡ lỗi", statusReady: "SẴN SÀNG", statusSubReady: "Nhấn Phím cách hoặc Nhấp vào đây để bắt đầu ghi âm", statusRec: "ĐANG GHI ÂM...", statusSubRec: "Hãy nói ngay bây giờ. Nhấn ENTER hoặc Nhấp vào đây để gửi.", statusProc: "ĐANG XỬ LÝ...", statusSubProc: "Đang chép lời và tạo phản hồi...", statusSpeak: "AI ĐANG NÓI...", statusSubSpeak: "Nghe phản hồi (Nhấp hoặc Nhấn Phím cách để Ngắt lời)", statusErr: "LỖI", statusSubErr: "Lỗi API. Hãy kiểm tra Trình kiểm tra.", userPlaceholder: "Lời nói của người dùng đã chép sẽ xuất hiện ở đây...", aiPlaceholder: "Phản hồi của trợ lý đã được làm sạch sẽ xuất hiện ở đây...", pasteKey: "Dán Khóa {provider}", reqKey: "Nhập khóa API cho mô hình đã chọn", credAvail: "Tín dụng khả dụng", noCred: "Không có tín dụng khả dụng", credLeft: "Tín dụng: còn lại {rem} / {limit} ký tự", ctrls: "<strong>[ PHÍM CÁCH ]</strong> Ghi âm/Tạm dừng/Ngắt lời | <strong>[ ENTER ]</strong> Gửi | <strong>[ ESC ]</strong> Xóa Bộ nhớ", basic: "Cơ bản", fast: "Nhanh", expressive: "Biểu cảm", slow: "Chậm", conversational: "Trò chuyện", soft: "Mềm mại", confident: "Tự tin", playful: "Vui tươi", warm: "Ấm áp", errMic: "Quyền truy cập micrô bị từ chối.", errKeys: "Vui lòng nhập cả Khóa API Chuyển giọng nói thành Văn bản và Động cơ AI."
  },
  ru: {
    uiLang: "Язык Интерфейса", stt: "Провайдер Преобразования Речи в Текст", tts: "Провайдер Преобразования Текста в Речь", lang: "Язык Ассистента", voice: "Голос Ассистента", llm: "Провайдер ИИ-Движка (LLM)", inst: "Инструкции для Голосового Ассистента", user: "Запрос Пользователя", ai: "Ответ Голосового Ассистента", clear: "Очистить Память (ESC)", debug: "Включить Инспектор Отладки", statusReady: "ГОТОВ", statusSubReady: "Нажмите Пробел или Кликните здесь, чтобы начать запись", statusRec: "ЗАПИСЬ...", statusSubRec: "Говорите сейчас. Нажмите ENTER или Кликните здесь, чтобы отправить.", statusProc: "ОБРАБОТКА...", statusSubProc: "Транскрибация и генерация ответа...", statusSpeak: "ИИ ГОВОРИТ...", statusSubSpeak: "Слушайте ответ (Кликните или нажмите Пробел, чтобы прервать)", statusErr: "ОШИБКА", statusSubErr: "Ошибка API. Проверьте Инспектор.", userPlaceholder: "Распознанная речь пользователя появится здесь...", aiPlaceholder: "Обработанный ответ ассистента появится здесь...", pasteKey: "Вставьте Ключ {provider}", reqKey: "Введите API-ключ для выбранной модели", credAvail: "Кредиты доступны", noCred: "Нет доступных кредитов", credLeft: "Кредиты: осталось {rem} / {limit} символов", ctrls: "<strong>[ ПРОБЕЛ ]</strong> Запись/Пауза/Прервать | <strong>[ ENTER ]</strong> Отправить | <strong>[ ESC ]</strong> Очистить Память", basic: "Базовый", fast: "Быстрый", expressive: "Выразительный", slow: "Медленный", conversational: "Разговорный", soft: "Мягкий", confident: "Уверенный", playful: "Игривый", warm: "Теплый", errMic: "Доступ к микрофону запрещен.", errKeys: "Пожалуйста, введите API-ключи для Преобразования Речи в Текст и ИИ-Движка."
  }
};

// Add fallback dynamically mapping all other languages to the full English keys, 
// replacing them dynamically using proper dictionary fallback structure so NOTHING remains barebones.
const baseLangs = ["pt", "nl", "hi", "tr", "pl", "sv", "bg", "ro", "ar", "cs", "el", "fi", "hr", "ms", "sk", "da", "ta", "uk", "hu", "no", "id", "tl"];
baseLangs.forEach(lang => {
  UI_TRANSLATIONS[lang] = Object.assign({}, UI_TRANSLATIONS.en);
});

